import type { Metadata } from "next";
import "./globals.css";
import FormProvider from "@/contexts/FormContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <FormProvider>
        <body className="font-ubuntu">
          {/* BG OVERLAY */}
          <div className="absolute h-full w-full bg-light-gray -z-10"></div>
          {/* MAIN */}
          <main className="sm:h-screen min-h-screen flex flex-col items-center justify-center px-4 sm:px-12 relative">
            {children}
          </main>
        </body>
      </FormProvider>
    </html>
  );
}
