import type { Metadata } from "next";
import "./globals.css";
import FormProvider from "@/contexts/FormContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <FormProvider>
        <body className="font-ubuntu">
          <main className="h-screen min-h-screen bg-light-gray flex flex-col items-center justify-center px-8 sm:px-12 ">
            {children}
          </main>
        </body>
      </FormProvider>
    </html>
  );
}
