import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { fetchUser } from "@/stores/user-store";
import { store } from "@/stores";
import StoreHydraProvider from "@/stores/StoreHydraProvider";

const BodyFont = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await store.dispatch(fetchUser());
  const user = store.getState().user.user;

  return (
    <html lang="en">
      <StoreHydraProvider preloadedState={{ user: { user } }}>
        <body className={BodyFont.className}>
          <Header />
          <main>{children}</main>
        </body>
      </StoreHydraProvider>
    </html>
  );
}
