import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { fetchUser } from "@/stores/user-store";
import { store } from "@/stores";
import StoreProvider from "@/stores/StoreProvider";

const BodyFont = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // console.log(store.getState());
  await store.dispatch(fetchUser());

  return (
    <html lang="en">
      <StoreProvider>
        <body className={BodyFont.className}>
          <Header />
          <main>{children}</main>
        </body>
      </StoreProvider>
    </html>
  );
}
