import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#131c2f] text-[#eee]`}>
        <main className="h-screen mx-auto flex flex-col items-center text-2xl">
          <Navbar />
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
}
